name: Python application with Allure reporting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest allure-pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests with Allure reporting
      run: |
        pytest -k 'test_home_pom' dsl/ui/pages/totaljobs/home.py --alluredir=allure-results
        pytest -k 'test_search_results_pom' dsl/ui/pages/totaljobs/search_results.py --alluredir=allure-results
    - name: Publish Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
        force_orphan: true
